<?php

namespace TurnierplanBundle\Repository;

/**
 * EndrundenspielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndrundenspielRepository extends \Doctrine\ORM\EntityRepository
{
}
