<?php

namespace TurnierplanBundle\Repository;

/**
 * HauptrundenspielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HauptrundenspielRepository extends \Doctrine\ORM\EntityRepository
{
}
