<?php

namespace TurnierplanBundle\Repository;

/**
 * JugendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugendRepository extends \Doctrine\ORM\EntityRepository
{
}
