<?php

namespace TurnierplanBundle\Repository;

/**
 * SpielplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpielplanRepository extends \Doctrine\ORM\EntityRepository
{
}
