<?php

namespace TurnierplanBundle\Repository;

/**
 * SpielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpielRepository extends \Doctrine\ORM\EntityRepository
{
}
