<?php

namespace TurnierplanBundle\Repository;

/**
 * TurniertagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurniertagRepository extends \Doctrine\ORM\EntityRepository
{
}
