<?php

namespace TurnierplanBundle\Repository;

/**
 * VorrundenspielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VorrundenspielRepository extends \Doctrine\ORM\EntityRepository
{
}
