<?php

namespace TurnierplanBundle\Repository;

/**
 * VorrundenspielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VorrundenspielRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGespielteSpiele($altersklasse)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('TurnierplanBundle:Spiel', 'p')
            ->where(
                $qb->expr()->isNotNull('p.ergGast'),
                $qb->expr()->isNotNull('p.ergHeim'),
                $qb->expr()->eq('p.altersklasse', $altersklasse->getId())
            )
            ->getQuery();

        return $q->getResult();
    }
}
