<?php

namespace AppBundle\Repository;

/**
 * RolleeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolleeRepository extends \Doctrine\ORM\EntityRepository
{
}
