# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.submit_type_extension:
    class: TeilnehmerBundle\Form\Extension\SubmitTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\SubmitType }

  app.form.registration:
    class: UserBundle\Form\GroupFormType
    tags:
       - { name: form.type, alias: app_group }