<?php

namespace TeilnehmerBundle\Repository;
use TurnierplanBundle\TurnierplanBundle;

/**
 * MannschaftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MannschaftRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMannschaftByStatusCompare($status,$altersklasse)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('TeilnehmerBundle:Mannschaft', 'p')
            ->where(
                $qb->expr()->gte('p.status', $status),
                $qb->expr()->eq('p.altersklasse', $altersklasse->getId())
            )
            ->getQuery();

        return $q->getResult();
    }
}
