<?php

namespace TeilnehmerBundle\Repository;

/**
 * MannschaftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MannschaftRepository extends \Doctrine\ORM\EntityRepository
{
}
