<?php

namespace TeilnehmerBundle\Repository;

/**
 * SchiedsrichterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchiedsrichterRepository extends \Doctrine\ORM\EntityRepository
{
}
