<?php

namespace TeilnehmerBundle\Repository;

/**
 * UnterkunftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnterkunftRepository extends \Doctrine\ORM\EntityRepository
{
}
