<?php

namespace TeilnehmerBundle\Repository;

/**
 * VereinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VereinRepository extends \Doctrine\ORM\EntityRepository
{
}
